[package]
name = "assets"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10.13"
ic-cdk = "0.17.1"
ic-certified-assets = { git = "https://github.com/dfinity/sdk.git" }