name: Deploy canisters

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup dfx
        uses: aviate-labs/setup-dfx@v0.3.2
        with:
          dfx-version: 0.18.0
        env:
          DFX_IDENTITY_PEM: ${{ secrets.IDENTITY_KEY }}
        run: dfx identity use action

      - name: Deploy to the IC
        run: dfx deploy --network ic --no-wallet
