name: Deploy canisters

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup dfx
        uses: aviate-labs/setup-dfx@v0.3.2
        with:
          dfx-version: 0.18.0
        env:
          DFX_IDENTITY_PEM: ${{ secrets.DFX_IDENTITY_PEM }}

      - run: |
          dfx identity use action
          dfx deploy --network ic --no-wallet

      - name: Deploy
        env:
          IC_SIWE_PROVIDER_SALT: ${{ secrets.IC_SIWE_PROVIDER_SALT }}
          TAG_KEY: ${{ secrets.TAG_KEY }}
        run:
          ./setup.sh -n ic
