name: Deploy canisters

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup dfx
        uses: aviate-labs/setup-dfx@v0.3.2
        with:
          dfx-version: 0.18.0

      - run: |
          echo "$PEM_KEY" > dev_key.pem
          dfx identity import dev dev_key.pem
          chmod 600 my_key.pem
          dfx identity use dev
        env:
          PEM_KEY: "${{ secrets.DFX_IDENTITY_PEM }}"

      - name: Deploy
        env:
          IC_SIWE_PROVIDER_SALT: ${{ secrets.IC_SIWE_PROVIDER_SALT }}
          TAG_KEY: ${{ secrets.TAG_KEY }}
        run:
          ./setup.sh -n ic
